### ISSUE TITLE
[ENHANCEMENT]: stubEndpointForHttpRequest request comparison requires fields to be in order

### ISSUE THREAD

**Issue by benkiefer** [toranb/ember-cli-test-helpers#19]
Otherwise you get a comparison error in your tests.

**Comment by toranb** [comment]
Agreed -found this myself recently as you are comparing 1 string to another :(

**Comment by williamsbdev** [comment]
I believe this issue is resolved. There were changes that were made to this library, [ember-promise](https://github.com/toranb/ember-promise) and [fauxjax](https://github.com/jarrodctaylor/fauxjax).

To have best results, it is recommended to use these versions:

ember-promise: 1.2.0
ember-cli-test-helpers: 1.6.0
fauxjax: 1.2.1
